# BarnabeeNet Core Services
# Phase 1: Foundation services only
version: "3.8"

services:
  redis:
    image: docker.io/redis:7-alpine
    container_name: barnabeenet-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - /home/thom/data/redis:/data:Z
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  prometheus:
    image: docker.io/prom/prometheus:v2.48.0
    container_name: barnabeenet-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - /home/thom/data/prometheus:/prometheus:Z
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      - "--web.enable-lifecycle"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: docker.io/grafana/grafana:10.2.2
    container_name: barnabeenet-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /home/thom/data/grafana:/var/lib/grafana:Z
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=barnabeenet
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://192.168.86.51:3000
      - GF_INSTALL_PLUGINS=
    depends_on:
      - prometheus
    healthcheck:
      test:
        ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
